SELECT P.PRODUCT_CODE, (P.PRICE * R.AMOUNT) AS SALES
FROM PRODUCT P
JOIN (
SELECT O.PRODUCT_ID, SUM(O.SALES_AMOUNT) AS AMOUNT
FROM OFFLINE_SALE O
GROUP BY PRODUCT_ID) AS R
ON P.PRODUCT_ID = R.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC;