# 1. 11월에 예약중인 차의 아이디 찾기
# 11월 1일 이전에 시작해 12월 1일 이후에 끝나는 모든 차량 기록
# SELECT CAR_ID
# SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE < '2022-11-01'
# AND END_DATE > '2022-12-01';

# # 2. 1을 예외처리하는 차량 아이디 출력
SELECT CAR_ID, CAR_TYPE, FEE
FROM (
SELECT CAR_ID, CAR_TYPE, FLOOR(DAILY_FEE * 30 * (
    SELECT (100 - DISCOUNT_RATE) * 0.01
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = C.CAR_TYPE
    AND DURATION_TYPE = '30일 이상'
))
 AS FEE                              
FROM CAR_RENTAL_COMPANY_CAR AS C
WHERE CAR_ID NOT IN
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (START_DATE <= '2022-11-30')
AND (END_DATE >= '2022-11-01')
GROUP BY CAR_ID)
AND CAR_TYPE IN ('세단', 'SUV')) AS T
WHERE fee >= 500000 AND fee < 2000000
ORDER BY fee DESC, car_type ASC, car_id DESC