# 2. 1에서 세단, suv만 고른다
SELECT CAR_ID, CAR_TYPE, FLOOR(DAILY_FEE * 30 * (
    # 3. CALC DISCOUNT RATE
    SELECT (100 - DISCOUNT_RATE) * 0.01
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
    AND C.CAR_TYPE = CAR_TYPE
)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
WHERE CAR_TYPE IN ('세단', 'SUV')
AND CAR_ID NOT IN 
    # 1. 11월 1일부터 30일까지 차량 고르기 - 나중에 거른다.
    (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30'
    AND END_DATE > '2022-11-01'
    GROUP BY CAR_ID);
   
# 4. FILTERING
SELECT CAR_ID, CAR_TYPE, FEE
    FROM (# 2. 1에서 세단, suv만 고른다
    SELECT CAR_ID, CAR_TYPE, FLOOR(DAILY_FEE * 30 * (
        # 3. CALC DISCOUNT RATE
        SELECT (100 - DISCOUNT_RATE) * 0.01
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE DURATION_TYPE = '30일 이상'
        AND C.CAR_TYPE = CAR_TYPE
    )) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    WHERE CAR_TYPE IN ('세단', 'SUV')
    AND CAR_ID NOT IN 
        # 1. 11월 1일부터 30일까지 차량 고르기 - 나중에 거른다.
        (SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30'
        AND END_DATE > '2022-11-01'
        GROUP BY CAR_ID)
) AS T
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;