SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A
JOIN
(SELECT FOOD_TYPE, MAX(FAVORITES) AS CNT
FROM REST_INFO
GROUP BY FOOD_TYPE) B 
ON A.FAVORITES = B.CNT
GROUP BY A.FOOD_TYPE
ORDER BY A.FOOD_TYPE DESC;