# 2. 헤비유저의 데이터 조회
SELECT ID, NAME, HOST_ID
FROM PLACES
JOIN (
    # 1. 헤비유저 추려내기
    SELECT HOST_ID AS H
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID) >= 2 
) AS RESULT
WHERE PLACES.HOST_ID = RESULT.H
ORDER BY ID;